import type { CollectionEntry } from "astro:content";

/** Astro content collection entry for a published or draft article. */
export type ArticleEntry = CollectionEntry<"articles">;

/** Astro content collection entry for category metadata. */
export type CategoryEntry = CollectionEntry<"categories">;

/** Display-ready category data with its sorted articles. */
export interface CategorySummary {
  articles: ArticleEntry[];
  description?: string | undefined;
  order: number;
  slug: string;
  title: string;
}

export const SITE_TITLE = "The Philosopher's Meme";
export const SITE_DESCRIPTION =
  "The philosophy of memes, cyberculture, and the Internet.";

function withTrailingSlash(path: string) {
  if (path === "") {
    return "/";
  }
  return path.endsWith("/") ? path : `${path}/`;
}

/**
 * Builds the canonical site URL path for an article slug.
 *
 * @param slug Article slug generated from the content entry ID.
 * @returns Absolute-path URL with the configured trailing slash.
 */
export function articleUrl(slug: string) {
  return withTrailingSlash(`/articles/${slug}`);
}

/**
 * Builds the canonical site URL path for a category slug.
 *
 * @param slug Category slug.
 * @returns Absolute-path URL with the configured trailing slash.
 */
export function categoryUrl(slug: string) {
  return withTrailingSlash(`/categories/${slug}`);
}

/**
 * Converts free-form text into the URL-safe slug format used by the site.
 *
 * @param value Raw text to normalize.
 * @returns Lowercase dash-separated slug text.
 */
export function normalizeSlug(value: string) {
  return value
    .trim()
    .toLowerCase()
    .replace(/&/g, "and")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "");
}

/**
 * Decodes the small set of HTML entities still present in legacy frontmatter.
 *
 * @param value Text that may include numeric or common named HTML entities.
 * @returns Text with supported entities decoded.
 */
export function decodeHtmlEntities(value: string) {
  return value
    .replace(/&#(\d+);/g, (_, codePoint: string) =>
      String.fromCodePoint(Number(codePoint)),
    )
    .replace(/&#x([0-9a-f]+);/gi, (_, codePoint: string) =>
      String.fromCodePoint(Number.parseInt(codePoint, 16)),
    )
    .replace(/&quot;/g, '"')
    .replace(/&apos;/g, "'")
    .replace(/&#39;/g, "'")
    .replace(/&amp;/g, "&")
    .replace(/&lt;/g, "<")
    .replace(/&gt;/g, ">");
}

/**
 * Reads an article title as user-facing text.
 *
 * @param entry Article content entry.
 * @returns Decoded article title.
 */
export function entryTitle(entry: ArticleEntry) {
  return decodeHtmlEntities(entry.data.title);
}

/**
 * Reads the stable URL slug for an article.
 *
 * @param entry Article content entry.
 * @returns Article slug generated by Astro's content collection ID.
 */
export function articleSlug(entry: ArticleEntry) {
  return entry.id;
}

/**
 * Reads the category slug from an article's source path.
 *
 * @param entry Article content entry.
 * @returns Category folder slug, or an empty string when no category is found.
 */
export function categorySlug(entry: ArticleEntry) {
  const filePath = entry.filePath ?? "";
  const marker = "/src/content/articles/";
  const relativePath = filePath.includes(marker)
    ? (filePath.split(marker)[1] ?? "")
    : filePath.replace(/^src\/content\/articles\//, "");

  return relativePath.includes("/") ? (relativePath.split("/")[0] ?? "") : "";
}

/**
 * Checks whether an article should be included in public site surfaces.
 *
 * @param entry Article content entry.
 * @returns True when the article is not marked as a draft.
 */
export function isPublishedArticle(entry: ArticleEntry) {
  return !entry.data.draft;
}

/**
 * Reads the publication date for an article.
 *
 * @param entry Article content entry.
 * @returns Article publication date.
 */
export function entryDate(entry: ArticleEntry) {
  return entry.data.date;
}

/**
 * Formats a date for reader-facing article metadata.
 *
 * @param date Date to format.
 * @returns Localized date text, or an empty string for missing/invalid dates.
 */
export function formatDate(date: Date | undefined) {
  if (date === undefined || Number.isNaN(date.getTime())) {
    return "";
  }
  return new Intl.DateTimeFormat("en", {
    day: "numeric",
    month: "long",
    year: "numeric",
  }).format(date);
}

/**
 * Reads the display author for an article.
 *
 * @param entry Article content entry.
 * @returns Author display name.
 */
export function authorName(entry: ArticleEntry) {
  return entry.data.author;
}

/**
 * Reads the article description used in cards, feeds, and metadata.
 *
 * @param entry Article content entry.
 * @returns Article description.
 */
export function excerpt(entry: ArticleEntry) {
  return entry.data.description;
}

function imageSource(value: unknown) {
  if (
    typeof value === "object" &&
    value !== null &&
    "src" in value &&
    typeof value.src === "string"
  ) {
    return value.src;
  }

  return undefined;
}

/**
 * Reads the resolved image URL for an article image field.
 *
 * @param entry Article content entry.
 * @returns Image URL when the article has an image.
 */
export function imageUrl(entry: ArticleEntry) {
  return imageSource(entry.data.image);
}

/**
 * Sorts articles by newest publication date, with slug as a stable tiebreaker.
 *
 * @param entries Article entries to sort.
 * @returns New sorted array without mutating the input.
 */
export function sortNewestFirst(entries: ArticleEntry[]) {
  return [...entries].sort((a, b) => {
    const bTime = entryDate(b).getTime();
    const aTime = entryDate(a).getTime();
    const dateSort = bTime - aTime;
    return dateSort !== 0
      ? dateSort
      : articleSlug(a).localeCompare(articleSlug(b));
  });
}

/**
 * Fails fast when multiple article entries resolve to the same public slug.
 *
 * @param entries Article entries to validate.
 */
export function assertUniqueArticleSlugs(entries: ArticleEntry[]) {
  const seen = new Map<string, string>();

  for (const entry of entries) {
    const slug = articleSlug(entry);
    const previous = seen.get(slug);

    if (previous !== undefined) {
      throw new Error(
        `Duplicate article slug "${slug}" for "${previous}" and "${entry.id}".`,
      );
    }

    seen.set(slug, entry.id);
  }
}
